### ISSUE TITLE
Excel::IsPasswordProtected seams broken or just not needed?

### ISSUE THREAD

**Issue by mbfx** [Sicos1977/OfficeExtractor#1]
Hi there,

at first: Thank you for that great component!

I have some questions/issue about password protected files, especially excel files.
1. The tests DocxWithPassword, PptxWithPassword and XlsWithPassword are currently not passed
I am wondering if they got broken or never worked.

2. Excel::IsPasswordProtected throws on Excel95 that the stream "WorkBook" doesn't exists
Maybe I would fix this, but:

3. I was unable to protect even a Excel 97 file in a way that IsPasswordProtected returns true. Even I protect if from opening, it returns false. It also returns false for your XlsWithPassword test.
Maybe again, this could be fixed, but:

4. Extraction works also for full password protected excel files I can't even open in Excel. All files are correctly exported.

5. The protection of the Xlsx test file (Excel >= 2007) is correctly detected, but the detection is just by checking for the "EncryptedPackage" stream. So for what revision of Excel is all the code with the "WorkBook" stream? I haven't tested if the export would be possible for such a protected 2007 document. I guess the protection is working in that case.

So at the end: Is IsPasswordProtected really needed ? Is it needed for Excel > 97 ?

**Comment by Sicos1977** [comment]
I fixed your issues... for some reason I committed some old code instead of a new version

**Comment by mbfx** [comment]
Great, I've seen the trunk assembly revision is below the last release (1.4.0 vs. 1.4.1).

**Comment by Sicos1977** [comment]
Just for my own curiosity ... for what are you using it?

**Comment by mbfx** [comment]
Again: Great! Thanks for the new release! I will delete my fork now.
To your question: I am working on a product converting documents, images ... into a PDF.

Your component is used to extract the embedded files. After that, the document itself and all its embedded files are converted into a single PDF file.

**Comment by Sicos1977** [comment]
Nice... I also made a document converter server... it's also the place where this component was born... to extract embedded PDF's and files like that from Office documents... we do about 25.000 conversions each day.

I have some more components on GitHub that are also related to document conversion

- https://github.com/Sicos1977/MSGReader
- https://github.com/Sicos1977/OfficeConverter
- https://github.com/Sicos1977/VCardReader
- https://github.com/Sicos1977/PDFSplitter
-

**Comment by mbfx** [comment]
Cool!
Just asking: I compiled the release myself now, so no hurry: Will you update the official nuget.org package?

**Comment by Sicos1977** [comment]
I'll do it this evening... I'm at work now...

**Comment by mbfx** [comment]
Thanks for all!

**Comment by Sicos1977** [comment]
If you need to convert HTML then use this --> http://wkhtmltopdf.org/

There is also an excellent .NET wrapper for it --> https://github.com/tuespetre/TuesPechkin

**Comment by mbfx** [comment]
I somewhat come in a dependency trouble:
1.4.1 nuget.org release:
https://www.nuget.org/packages/OfficeExtractor/ said "CompoundFileStorage (>= 1.3.1)"
If I add the the component using this, it tries to install CompoundFileStorage 1.3.1.

The trunk+1.4.2+1.4.1 source:
If I open the solution CompoundFileStorage 1.0.0.0 is used.
OfficeExtractor\packages.config -> 1.0.0.0

So is the change with the dependency missing in the available source?

**Comment by mbfx** [comment]
I discussed with a college about that: he told me the nuget.org OfficeExtractor package references 1.3.1.0 of the CompoundFileStorage but the assembly with that and he found out the assembly itself needs 1.0.0.0. He was needed to enforce installing the older revision, otherwise it crashed. Maybe this is some additional information for this.

**Comment by Sicos1977** [comment]
I'll make a new version of the office extractor that doesn't need the compoundfilestorage anymore. I originally made the compoundfilestorage dll because it was an upgrade from OpenMCDF to .NET 4.0. But since a year there is a much newer OpenMCDF version. So in the next release I will incorporate that and get rid of the compoundfilestorage assembly

**Comment by Sicos1977** [comment]
A new package has been published to NuGet (the one with the OpenMCDF dependency instead of my old CompoundFileStorage assembly)

**Comment by Sicos1977** [comment]
Also a tip for you document converter, don't always look to the extension of the file. For some reason users for example mange to put a .doc extension on a .pdf file. When a conversion fails then try to detect the type with this class --> https://github.com/Sicos1977/OfficeExtractor/blob/master/OfficeExtractor/Helpers/FileTypeSelector.cs

It looks to the "magic bytes" to determine the file type instead of the extension.

If you need any help with something else then let me now :-) ... I have done tons of work with converter files to other formats.
