### ISSUE TITLE
Embedded Object Name

### ISSUE THREAD

**Issue by darren718** [Sicos1977/OfficeExtractor#14]
Hello there, 
I was wondering if there is a way to display the names of the embedded objects after the extraction instead of just "Embedded object.docx", "Embedded Word document.doc" etc.
Thanks.

**Comment by Sicos1977** [comment]
This could probably be possible by opening the Word document and reading the properties stream. The filename could be possible somewhere in there. But that is something that is currently not implemented.

**Comment by darren718** [comment]
Alright, thanks for the info.

**Comment by Sicos1977** [comment]
Can you send me the file that was giving you the "Embedded Word document.doc" as output? This way I can figure out if it is possible and how much work that would take me.

You can send the file to sicos2002@hotmail.com

**Comment by darren718** [comment]
Hey Kees,
I have sent you an email, did you receive it?
