### ISSUE TITLE
there're 2 issues

### ISSUE THREAD

**Issue by luoyunfeng2016** [Sicos1977/OfficeExtractor#15]

**Comment by luoyunfeng2016** [comment]
1.OfficeExtractor.Helpers.Strings.ReadNullTerminatedAnsiString, this function can't support GBK. I fix it:
   internal static string ReadNullTerminatedAnsiString(BinaryReader binaryReader)
        {
            /*
            var stringBuilder = new StringBuilder();

            while (binaryReader.PeekChar() != -1)
            {
                var b = binaryReader.ReadByte();
                if (b == 0)
                    return stringBuilder.ToString();

                stringBuilder.Append((char)b);
            }

            return stringBuilder.ToString();
            */
            byte[] bytes = new byte[1024];
            int index = 0;
            do
            {
                var b = binaryReader.ReadByte();
                bytes[index++] = b;
                if (b == 0)
                    break;                
            }while(true);
            byte[] bytes_unicode = Encoding.Convert(Encoding.Default, Encoding.Unicode, bytes);
            var str = Encoding.Unicode.GetString(bytes_unicode);
            return str.TrimEnd('\0');
        }

**Comment by luoyunfeng2016** [comment]
2. If the emedded files is not in stream "\x0001Ole10Native" or "\x0003ObjInfo", it can't be extracted.
    you can make the embedded file like this method: Office Menu Insert -> Object -> New, you can new one office97-2003 word file, the embedded file will be original stream. You can fix it via modifying code at here:
OfficeExtractor.Word.SaveToFolder
{
……
……
/*
                        // Get the objInfo stream to check if this is a linked file... if so then ignore it
                        var objInfo = childStorage.GetStream("\x0003ObjInfo");
                        var objInfoStream = new ObjInfoStream(objInfo);

                        // We don't want to export linked objects and objects that are not shown as an icon... 
                        // because these objects are already visible on the Word document
                        if (objInfoStream.Link || !objInfoStream.Icon) return;
                        extractedFileName = Extraction.SaveFromStorageNode(childStorage, outputFolder);
                        */
                        // Get the objInfo stream to check if this is a linked file... if so then ignore it
                        var objInfo = childStorage.GetStream("\x0003ObjInfo");
                        if (objInfo != null)
                        {
                            var objInfoStream = new ObjInfoStream(objInfo);

                            // We don't want to export linked objects and objects that are not shown as an icon... 
                            // because these objects are already visible on the Word document
                            if (objInfoStream.Link || !objInfoStream.Icon) return;
                        }
                        extractedFileName = Extraction.SaveFromStorageNode(childStorage, outputFolder);
……
……
}

**Comment by luoyunfeng2016** [comment]
Your code is very great!!

**Comment by luoyunfeng2016** [comment]
Oh, I'm sorry, the method to fix the 2nd issue is wrong, but i'm sure, this code "if (objInfoStream.Link || !objInfoStream.Icon) return;" has some issue, the embedded file is not Link and is not Icon, it's QueriedEmf

**Comment by Sicos1977** [comment]
Implemented
