### ISSUE TITLE
PasswordProtectedChecker Dependency not Reflected in NuGet-Package

### ISSUE THREAD

**Issue by bormm** [Sicos1977/OfficeExtractor#16]
I don't know how this stuff works, but the Assembly can't be used anymore without "PasswordProtectedChecker, Version=1.3.0.0, Culture=neutral, PublicKeyToken=61be40572173cc31". But the nuget-package does not shows this dependency and so is not automatically installing it.

**Comment by Sicos1977** [comment]
Oeps... I'll check the package and fix it this evening.

**Comment by Sicos1977** [comment]
I have published a new package 1.8.1 that has the correct dependicies
