### ISSUE TITLE
How to Use or Invoke?

### ISSUE THREAD

**Issue by MarkAStevens** [Sicos1977/OfficeExtractor#17]
I have downloaded from github, and have it as a project. A solution file exists, so it seems complete. However, I have not been able to determine how to run it against an MS Office document.

Usage? [C:\path\to\]OfficeExtractor [flags?] MySpreadSheet.xlsx

Thanks!

**Comment by Sicos1977** [comment]
The solution has a test program that shows you how you can invoke the officeextractor assembly
