### ISSUE TITLE
PasswordProtectedChecker Dependency

### ISSUE THREAD

**Issue by dign17** [Sicos1977/OfficeExtractor#19]
Hello Kees,

with the latest OfficeExtractor release **1.8.1** you added a **PasswordProtectedChecker** dependency which relies on the **iTextSharp-LGPL** package. I can think of a scenario where the current usage of `public Result IsFileProtected(string fileName)` inside the **Extractor** class is convenient, but it also implicates a problem of potentially conflicting dependencies. In addition it is now also necessary to comply with LGPL rules, due to a dependency of OfficeExtractor and not the component itself.

For more simplicity could you consider to move the usage of **PasswordProtectedChecker** outside of **OfficeExtractor**?

With kind regards

Dmitry

**Comment by Sicos1977** [comment]
If you know another tool with another license type that I can use to check if a PDF is password protected then I'm okay with that. The reason why is used the iTextSharp LGPL version is so that you can still use it in closed source applications

**Comment by dign17** [comment]
Thank you for the response. 

My main concern was not the license of the **iTextSharp** package, but the need of the **PasswordProtectedChecker** as an **OfficeExtractor** dependency. Currently the Extractor just throws an exception in case the input file is password protected, which in my opinion can be performed outside of the project explicitly including the necessary dependency.

It seems a little bit odd to me to have a PDF library as mandatory dependecy even though the OfficeExtractor itself can not handle a PDF as input only as attachment. Of course I also understand the convenience of the setup as well.

**Comment by Sicos1977** [comment]
For easy in handling I moved all the code that checks if something is password protected to an assembly. I use this assembly in more then one project. It's easier for me to maintain it this way.

**Comment by dign17** [comment]
To make it more modular and solve my issues, the part for password checking the office files could be moved to a separate project called e.g. **PasswordProtectedChecker.Office** and added as a dependency to the main **PasswordProtectedChecker** and **OfficeExtractor** as well.

If we can agree on that, I would fork the **PasswordProtectedChecker**, modify the code accordingly and create a pull request. Additionally I would create a separate **PasswordProtectedChecker.Office** project containing the missing functionality to be added as dependency. You could then fork it and continue maintaining.

**Comment by Sicos1977** [comment]
I'll first try to look for code that can check PDF's without needing iTextSharp LGPL. If I can't find anything for that I'll fork the code and move the PDF code out of it.

**Comment by Sicos1977** [comment]
I think I found a solution for iTextSharp. It seems that pdfsharp (MIT license) also has code to check for a pdf password. I'll try to copy the code that checks if the file is password protected and move that one into the assembly. This will remove the dependency for iTextSharp.

http://www.pdfsharp.net/wiki/(X(1)S(doqb1bzsj0lrpgtkkrg5v0jw))/Default.aspx?Page=ProtectDocument-sample&NS=&AspxAutoDetectCookieSupport=1

**Comment by dign17** [comment]
Just for better understanding, if you say 

> I'll try to copy the code that checks if the file is password protected

do you mean

**A**: replacing _iTextSharp_ by _PDFsharp_ 

OR

**B**: taking the part of the source code from _PDFsharp_ and using it in _PasswordProtectedChecker_ without any dependencies?

**Comment by Sicos1977** [comment]
B when possible

**Comment by Sicos1977** [comment]
I need the code that read the header from the PDF, it seems that that is all you need to check if a PDF is password protected.

**Comment by dign17** [comment]
Hello Kees,

I don't want to hassle, but do you have any update on the progress done so far?

With kind regards

**Comment by Sicos1977** [comment]
The iTextSharp depenency has been removed... it didn't work as I inteded anyways :-)
