### ISSUE TITLE
Embedded image objects in word 97-2003 documents cannot be extracted

### ISSUE THREAD

**Issue by mbfx** [Sicos1977/OfficeExtractor#2]
Hi Kees,

we just noticed that all embedded image objects (jpg,png) within word 97 files (stored using office 2007) are not extracted. I have seen that your test documents containing other office file objects and text files, but no images. Is there some special thing with images?

I tried the 1.4.1 and 1.4.3 release using the OfficeViewer with the attached test file.

Did you know anything about that?
[word97-with-embedded-images.zip](https://github.com/Sicos1977/OfficeExtractor/files/599734/word97-with-embedded-images.zip)

Best regards
Marco

**Comment by mbfx** [comment]
We have found out that the problem is the check if the object is embedded as Icon. For Office documents Icon=True means: the content is not visible. But at least within out Office 2007, the content of a image is not never visible. Embedded as object with an Icon or as an object without Icon makes no difference.

**Comment by Sicos1977** [comment]
I never tested it with embedded images... my original purpose was to extract pdf's and office files. I see if I can figure out some way to detect embedded images.

**Comment by Sicos1977** [comment]
I added support for embedded images in binary Word documents. I drafted a new release (version 1.4.4) on GitHub. Just let me know if it works for you so that I can publish a new nuget package.

**Comment by mbfx** [comment]
My colleague found out what the problem is: Of course on a standard setup the images are directly visible in Word if embedding a image file as OLE object without Icon. But we all got a Icon, even with "Icon=False".
The reason for that is: if you associated some other application with the extension, for example jpeg with IrfanView, Word is unable to render it and shows the icon from the associated application. I think maybe the associated application has to provide some OLE render interface and the most don't implement these.

My colleague found this link, with a identical problem:
https://knowledge.autodesk.com/support/autocad/troubleshooting/caas/sfdcarticles/sfdcarticles/OLE-image-files-are-displayed-as-icons-instead-of-images.html

So the situation is complex. Icon=False doesn't mean the object is visible, only that it should be visible.
In our case and I think also in yours the workaround could be simple: We have a server environment especially to convert documents. We will expect now that images are associated with MsPaint.

I have seen you already created a new release. We will check how this changes the situation, but this couldn't change the rendering behavior of Word. So I assume this would exports images which are already rendered in Word, if the registry is correctly configured.

**Comment by dign17** [comment]
Hello Kees,

thank you for adding the support on embedded images in binary word documents. It now works as expected.

Unfortunately we currently have another issue on embedded image (bmp,jpg) files in excel sheets. I opened a new issue for this (#3).

With kind regards

Dmitry

**Comment by mbfx** [comment]
I have to add a info to my existing comment: We had found out that the registry setting is only relevant at document creation time and not for rendering after creation the embedded image.

If there was no OLE image provider for the given file type at creation time, the shell icon is embedded (even it is not in Icon mode). So your fix is completely working for us. We don't know how exactly you did it, but it exports all needed images no more 👍

**Comment by Sicos1977** [comment]
At the moment I'm a little bit busy... I will try to look into it this evening.
