### ISSUE TITLE
Extracted file order does not match original oleObject order

### ISSUE THREAD

**Issue by nicolausdewitt** [Sicos1977/OfficeExtractor#21]
When there are 10 or more embedded objects, the order of the extracted files does not match the order of the original oleObject files.

Original Filename|New Filename
-- | --
oleObject1.bin | Embedded object.bin
oleObject10.bin | Embedded object_2.bin
oleObject11.bin | Embedded object_3.bin
oleObject2.bin | Embedded object_4.bin
oleObject3.bin | Embedded object_5.bin
oleObject4.bin | Embedded object_6.bin
oleObject5.bin | Embedded object_7.bin
oleObject6.bin | Embedded object_8.bin
oleObject7.bin | Embedded object_9.bin
oleObject8.bin | Embedded object_10.bin
oleObject9.bin | Embedded object_11.bin

I have fixed this in a local copy of Extractor.cs by reordering the list by extracting the oleObjectId from the URI:

                   // extracts the id of an oleobject so we can order it appropriately
                    Func<string, int> getOleObjectId = p => {
                        string fileName = p.Substring(p.LastIndexOf(@"/") + 1);
                        int objectId;
                        string retrievedId = fileName.ToLower().Replace("oleobject", "").Replace(".bin", "");
                        bool success = int.TryParse(retrievedId, out objectId);
                        return success ? objectId : 9999;
                    };

                    // Get the embedded files names in the correct order. 
                    var parts = package.GetParts()
                        .ToList()
                        .Where(p => p.Uri.ToString().StartsWith(embeddingPartString))
                        .OrderBy( p => getOleObjectId(p.Uri.ToString()) )
                        .ToList();

                    foreach (var packagePart in parts)

**Comment by Sicos1977** [comment]
I know that it is a long time ago, but where in the code did you use this?

**Comment by nicolausdewitt** [comment]
https://github.com/Sicos1977/OfficeExtractor/blob/master/OfficeExtractor/Extractor.cs#L428
