### ISSUE TITLE
Doesn't throw exceptions

### ISSUE THREAD

**Issue by Sh1nyAnd3o3** [Sicos1977/OfficeExtractor#24]
https://github.com/Sicos1977/OfficeExtractor/blob/02e74401995d67abf00836f03a5f440f613b9270/OfficeExtractor/Extractor.cs#L400

I assume there was no intention to just "log" the thrown exceptions, except if you use the attached test project...
Using the project in another application, (for example by using the nuget) could be problematic if the user intends to output possible errors, without using the workaround of regexing the exceptions out of the produced logfile ( or using the still exception throwing version 1.10.0)

**Comment by Sicos1977** [comment]
This was not intended, I shall fix it in a new version.

**Comment by Sicos1977** [comment]
Fixed --> https://github.com/Sicos1977/OfficeExtractor/releases/tag/1.14.1
