### ISSUE TITLE
While extracting entry '...docx' there was an error: Unsupported OleNative AnsiUserType 'Bitmap Image' foundUnsupported OleNative AnsiUserType

### ISSUE THREAD

**Issue by Sh1nyAnd3o3** [Sicos1977/OfficeExtractor#25]
Hello, while using the office extractor it returns this error message:

`While extracting entry '...docx' there was an error: Unsupported OleNative AnsiUserType 'Bitmap Image' foundUnsupported OleNative AnsiUserType`

We try to produce a file with this error, without sending personal data, but as a first question: is this issue known and may it be able to have this error fixed ?

**Comment by Sicos1977** [comment]
Well this error message is intended, I didn't know all AnsiUserType's that Word supports so I build in all the types I knew and needed and threw an exception if I came across something that was unknown to me.

So to make this answer clear, yes this is a known issue that I can fix but I need a document with that AnsyType in it to do it.

**Comment by Sh1nyAnd3o3** [comment]
Okey I can give you a sample file for this:
[Cleanup-LTRS1791.docx](https://github.com/Sicos1977/OfficeExtractor/files/6655571/Cleanup-LTRS1791.docx)

**Comment by Sh1nyAnd3o3** [comment]
Ahh there have been a miss understanding between me and a college, our problem is not exactly that the picture can't be extracted, in general we use the extractor for extracting files, except pictures! so is there a way to make the office extractor differentiate between those ?

**Comment by Sh1nyAnd3o3** [comment]
So to be accurate about what we need: because of the error thrown by the unsupported AnsiType of the image ( which intended to be part of the page and shouldn't be extracted) the office extractor throws an error and the actual content of the file doesn't get extracted, this content was removed in the sample I posted but it could be any file (pdf, exel etc).

**Comment by Sicos1977** [comment]
Well I can just ignore the image, that is what I also do overhere and you are right that the office extractors main purpose is to extract embedded files like PDF, Excel, etc....

Like I do here --> https://github.com/Sicos1977/OfficeExtractor/blob/master/OfficeExtractor/Ole/Ole10Native.cs

I'll try to fix this this evening or tomorrow.

**Comment by Sh1nyAnd3o3** [comment]
wonderful :) thanks

**Comment by Sicos1977** [comment]
I just released a new nuget package --> https://www.nuget.org/packages/OfficeExtractor/
