### ISSUE TITLE
Extracting ole objects - cannot load a non-seekable stream

### ISSUE THREAD

**Issue by StevenVerwerft** [Sicos1977/OfficeExtractor#26]
Hi,

I'm trying to use the OfficeExtractor nuget (v1.15.0) in a .NET5 project to extract pdf objects from docx files. however, the extractor keeps failing with an "OpenMcdf.CFException: Cannot load a non-seekable Stream".

Here's a snippet of the stack trace thrown in my unit test:
![image](https://user-images.githubusercontent.com/33197418/126764137-a16e6432-bc65-4194-95a1-e2c8c071d7b0.png)

I've done some research and you might want to change **packagePartStream** to **packagePartMemoryStream** in the constructor of the CompoundFile.
https://github.com/Sicos1977/OfficeExtractor/blob/898aded5e52178eeb8ed19592cf1987c4df62e39/OfficeExtractor/Extractor.cs#L438

Here's a reference to a related issue, where the suggestion also is to copy to a MemoryStream.
https://github.com/dotnet/runtime/issues/28258#issuecomment-468030220

Kind regards!

**Comment by StevenVerwerft** [comment]
Hi,
I made the adjustment on a fork. It seems to work for my needs.
https://github.com/StevenVerwerft/OfficeExtractor/commit/80328b9e7a37eb758ef345bfedd4825a6fe182d1

I'm unable to get the original unit tests to work. I believe because the test project is netframework 4.6. My unittests in a net5 testproject work fine. 

Do you want me to contribute?
Thanks in advance!

**Comment by Sicos1977** [comment]
Sure and I'm thinking about it to make just a seperate version for .net 5... only have to figure out how to do that in visual studio

**Comment by Sicos1977** [comment]
I just fixed the issue and uploaded a new nuget package https://www.nuget.org/packages/OfficeExtractor/1.16.0
