### ISSUE TITLE
Embedded image objects in excel documents cannot be extracted

### ISSUE THREAD

**Issue by dign17** [Sicos1977/OfficeExtractor#3]
Hello Kees,

we currently noticed that some embedded images formats (especially bmp and jpg) are not exported from excel sheets (.xls 97-2003 version). I also tested the newer excel container (.xlsx) where embedded .png and .tif work fine, but extracting .bmp and .jpg throws an exception stating a non valid value NULL (ViewerForm.cs line 85). 

For testing I used the 1.4.4 release and the file attached.
[EmbeddedBitmap.xlsx](https://github.com/Sicos1977/OfficeExtractor/files/603391/EmbeddedBitmap.xlsx)

For some strange reason I could not upload the .xls file as a zip, so sorry for this.

I guess this issue is somehow related to "Embedded image objects in word 97-2003 documents cannot be extracted #2" posted by Marco before. It would be nice if you have a solution for this one too.

With kind regards

Dmitry

**Comment by Sicos1977** [comment]
I added support for the embedded Excel images... but this had as a downside that some of my embedded images in Word are also extracted. I still have to figure out how to detect that... I will try to figure that out this week. This is very complex stuff :-)

**Comment by dign17** [comment]
Thank you for adding the functionality :+1:. Additonaly to the downside you mentioned above, it seems that JPGs are also extracted with the .bmp extension due to AnsiUserType equal to PBrush. I used the attached file for testing.

[EmbeddedBitmap.xlsx](https://github.com/Sicos1977/OfficeExtractor/files/608702/EmbeddedBitmap.xlsx)

**Comment by Sicos1977** [comment]
The JPG are converted to BMP when they are stored inside the Excel document. All what the code does is extract the daya so I can't help it that it not an JPG file anymore.... it is just the way how it works.

**Comment by dign17** [comment]
You are absolutely right of course, sorry for false alarming.

**Comment by Sicos1977** [comment]
I added logic to detect embedded images and if they are visible or not. I publised a new package on Nuget.

Have a nice weekend :-)

Greetings,
Kees van Spelde

**Comment by mbfx** [comment]
Great, thanks! It seams your AppVeyor reports an error now, due a failed test:
https://ci.appveyor.com/project/Sicos1977/officeextractor/build/1.0.15

**Comment by Sicos1977** [comment]
That one is fixed and I published a new package version 1.4.7
