### ISSUE TITLE
Strong Name Release?

### ISSUE THREAD

**Issue by bormm** [Sicos1977/OfficeExtractor#4]
After OpenMcdf is now available with a strong name, will OfficeExtractor also released (also on nuget.org) with a strong name?

**Comment by Sicos1977** [comment]
Sure ... if I don't forget it I will make a new package this evening. (I was the person that made the strong named OpenMcdf package :-) )

**Comment by Sicos1977** [comment]
A new package has been published to NuGet. You need version 1.4.9
