### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by dimmyr** [Sicos1977/OfficeExtractor#6]
How would I use this method so I can plug it into my powershell script that looks for macros inside Office files?  I am not real savvy with Visual Studio. I can use the compiled DLL file, I guess, but how do I make calls to it from my script?

**Comment by Sicos1977** [comment]
This project is not made to extract macro's. It's main goal is to extract embedded objects such as other documents. It should not be to hard to modify the code to do what you need though.

**Comment by dimmyr** [comment]
Thank you so much for responding! I asked because you commented on the officeparser.py git that yours doesn't the same job. I have no idea how to change your code to extract macro content. Would you mind giving me a pointer? ;)
Thank you so much!
